accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'), 
]

coincidence/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('market/', include('market.urls'))
]

market/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('BTC/', views.btcPrice, name='btcPrice'),
    path('ETH/', views.ethPrice, name='ethPrice'),
    path('transact/', views.transact, name='transact'),
] 

accounts/models.py
from django.db import models

# Create your models here.

market/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Balance(models.Model):
    """ Defines balance for each user"""
    username = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    usd_balance = models.DecimalField(max_digits=24, decimal_places=2)
    
    def __str__(self):
        return str(self.username) + " with usd of "+ str(self.usd_balance)
    
    def update_usd_balance(self, new_balance):
        """Updates the usd balance to the inputted balance"""
        self.usd_balance = new_balance


class Coin(models.Model):
    """Defines the name of the currency as well as the current held quantity. Tied to each balance"""
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True )
    
    coin_name = models.CharField(max_length = 60)
    quantity = models.DecimalField(default =0.0, max_digits=24, decimal_places=8) #Largest 16-digit number with 8 decimal places after
    
    def __str__(self):
        return str(self.owner) + " 's " + self.coin_name + " with quantity of " + str(self.quantity)
    
    def update_coin_quantity(self, new_balance):
        """Updates the coin balance to the inputted balance"""
        self.quantity = new_balance

market/forms.py
from django import forms

class QuantityForm(forms.Form):
    transact_quantity = forms.IntegerField()

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

market/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import User, Balance, Coin
from .forms import QuantityForm
from decimal import *



#SETTING DECIMAL BASED MATH
getcontext().prec = 8


def index(request):
    # return render(request, 'market/main.html')
    return HttpResponseRedirect(reverse('btcPrice'))
    
def btcPrice(request):
    return render(request, 'market/main.html')
    
    
def ethPrice(request):
    return render(request, 'market/ethPrice.html')
    
# def nanoPage(request):
#     return render(request, 'market/main.html')



def transact(request):
    """ Decides what happens with the Transact (buy/sell) POST request when it 
    is received """
    
    transactQuantity = Decimal(request.POST['transactionQuantity'])
    coin_type = request.POST['coin_type']
    transact_price = Decimal(request.POST['transact_price'])
    user_id = request.POST['user_id']
    submit_type = request.POST['submit_type']
    
    print("USER =", user_id )
    print (transactQuantity, coin_type, transact_price)
    
    
    if submit_type == 'buy':
        #BUY
        print ("BUYING")
        
        # subtract cost from usd balance
        cost = transactQuantity * transact_price
        user_balance = get_object_or_404(Balance,id=user_id)
        user_balance.update_usd_balance(user_balance.usd_balance - cost)
        user_balance.save()
        
        # add new coin quantity
        username = user_balance.username
        # coin_balance = Coin.objects.filter(owner__username__exact = user_id)
        coin_balance = get_object_or_404(Coin, owner__username__exact = username)
        coin_balance.update_coin_quantity( coin_balance.quantity + transactQuantity )
        print(coin_balance)
        coin_balance.save()
    
    elif submit_type == 'sell':
        #SELL
        print("SELLING")
        
        #Add revenue to usd balance
        revenue = transactQuantity * transact_price
        user_balance = get_object_or_404(Balance,id=user_id)
        user_balance.update_usd_balance(user_balance.usd_balance + revenue)
        user_balance.save()
        
        #Subtract from coin quantity
        username = user_balance.username
        coin_balance = get_object_or_404(Coin, owner__username__exact = username)
        coin_balance.update_coin_quantity( coin_balance.quantity - transactQuantity )
        coin_balance.save()
        
    else:
        print("RAISE EXCEPTION HERE")
    
        
        
    
    print("After")
    
    return HttpResponseRedirect(reverse('index'))
    

market/templates/market/ethPrice.html
{% extends 'base.html' %}
        
{% block content %}
<!-- A grey horizontal navbar that becomes vertical on small screens -->
<nav class="navbar navbar-expand-sm bg-light">
    <ul class="navbar-nav mr-auto">
        <!-- LOGO -->
        <a class="navbar-brand" href="{% url 'index' %}">Coin-cidence</a>
        
        <!-- Links -->
        <li class="nav-item">
            <a class="nav-link" href="{% url 'index' %}">BTC</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'ethPrice' %}">ETH</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">NANO</a>

    </ul>
    <ul class="navbar-nav">

        <li>
            <!-- Login/Logout button -->
        
            {% if user.is_authenticated %}
            Hello {{ user.username }}, you have a uninvested fund of ${{ user.balance.usd_balance }}!
            <a class="btn btn-primary" href="{% url 'logout' %}" role="button">Logout</a>
            {% else %}
            <p>You are not logged in</p>
            <a class="btn btn-primary" href="{% url 'login' %}" role="button">Login</a>
            {% endif %}
        
        </li>
    </ul>
</nav>



<!--Coin Status Jumbotron-->
<div class="jumbotron text-center">
        
        <h4>ETH Price (USD)</h4>
    
    
    <form action="{% url 'transact' %}" method="post">
        <input type="hidden" value="ETH" name="coin_type" id="coin_type"/>
        <input type="hidden" value="0" name="transact_price" id="transact_price"/>
        <input type="hidden" value={{user.id}} name="user_id" />
        
        
        
        <h1 class="display-1" id="BTC_price">Loading price data...</h1>
        
        <p></p>
        
    <!-- Action Buttons -->

    
        {% csrf_token %}
        <div class="form-group">
            <label for="transactionQuantity">Quantity:</label>
            <input id="transactionQuantity" name = "transactionQuantity" type="text" class="col-sm-2 col-form-label col-form-label-lg"   placeholder="Enter desired quantity">
            <small class="form-text text-muted">All transactions are final</small>
        </div>
    
        <button type="submit" name="submit_type" value="buy" class="btn btn-success">Buy</button> or
        <button type="submit" name="submit_type" value="sell" class="btn btn-danger">Sell</button>
    </form>
    

    

    
</div>


<p>Current Coin balances: </p>

{% for currency in user.coin_set.all %}
<p>{{currency.coin_name}} :  {{currency.quantity}}</p>
{% endfor %}




{% load static %}
<script src="{% static "market/js/script.js" %}"></script>


{% endblock %}

market/templates/market/main.html
{% extends 'base.html' %}
        
{% block content %}
<!-- A grey horizontal navbar that becomes vertical on small screens -->
<nav class="navbar navbar-expand-sm bg-light">
    <ul class="navbar-nav mr-auto">
        <!-- LOGO -->
        <a class="navbar-brand" href="{% url 'index' %}">Coin-cidence</a>
        
        <!-- Links -->
        <li class="nav-item">
            <a class="nav-link" href="{% url 'index' %}">BTC</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'ethPrice' %}">ETH</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">NANO</a>

    </ul>
    <ul class="navbar-nav">

        <li>
            <!-- Login/Logout button -->
        
            {% if user.is_authenticated %}
            Hello {{ user.username }}, you have a uninvested fund of ${{ user.balance.usd_balance }}!
            <a class="btn btn-primary" href="{% url 'logout' %}" role="button">Logout</a>
            {% else %}
            <p>You are not logged in</p>
            <a class="btn btn-primary" href="{% url 'login' %}" role="button">Login</a>
            {% endif %}
        
        </li>
    </ul>
</nav>



<!--Coin Status Jumbotron-->
<div class="jumbotron text-center">
        
        <h4>BTC Price (USD)</h4>
    
    
    <form action="{% url 'transact' %}" method="post">
        <input type="hidden" value="BTC" name="coin_type" id="coin_type" />
        <input type="hidden" value="0" name="transact_price" id="transact_price"/>
        <input type="hidden" value={{user.id}} name="user_id" />
        
        
        
        <h1 class="display-1" id="BTC_price">Loading price data...</h1>
        
        <p></p>
        
    <!-- Action Buttons -->

    
        {% csrf_token %}
        <div class="form-group">
            <label for="transactionQuantity">Quantity:</label>
            <input id="transactionQuantity" name = "transactionQuantity" type="text" class="col-sm-2 col-form-label col-form-label-lg"   placeholder="Enter desired quantity">
            <small class="form-text text-muted">All transactions are final</small>
        </div>
    
        <button type="submit" name="submit_type" value="buy" class="btn btn-success">Buy</button> or
        <button type="submit" name="submit_type" value="sell" class="btn btn-danger">Sell</button>
    </form>
    

    

    
</div>


<p>Current balances: </p>

{% for currency in user.coin_set.all %}
<p>{{currency.coin_name}} :  {{currency.quantity}}</p>
{% endfor %}




{% load static %}
<script src="{% static "market/js/script.js" %}"></script>


{% endblock %}

market/templates/market/nanoPrice.html
{% extends 'base.html' %}
        
{% block content %}
<!-- A grey horizontal navbar that becomes vertical on small screens -->
<nav class="navbar navbar-expand-sm bg-light">
    <ul class="navbar-nav mr-auto">
        <!-- LOGO -->
        <a class="navbar-brand" href="{% url 'index' %}">Coin-cidence</a>
        
        <!-- Links -->
        <li class="nav-item">
            <a class="nav-link" href="{% url 'index' %}">BTC</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'ethPrice' %}">ETH</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'nanoPrice' %}">NANO</a>

    </ul>
    <ul class="navbar-nav">

        <li>
            <!-- Login/Logout button -->
        
            {% if user.is_authenticated %}
            Hello {{ user.username }}, you have a uninvested fund of ${{ user.balance.usd_balance }}!
            <a class="btn btn-primary" href="{% url 'logout' %}" role="button">Logout</a>
            {% else %}
            <p>You are not logged in</p>
            <a class="btn btn-primary" href="{% url 'login' %}" role="button">Login</a>
            {% endif %}
        
        </li>
    </ul>
</nav>



<!--Coin Status Jumbotron-->
<div class="jumbotron text-center">
        
        <h4>Nano Price (USD)</h4>
    
    
    <form action="{% url 'transact' %}" method="post">
        <input type="hidden" value="NANO" name="coin_type" id="coin_type"/>
        <input type="hidden" value="0" name="transact_price" id="transact_price"/>
        <input type="hidden" value={{user.id}} name="user_id" />
        
        
        
        <h1 class="display-1" id="BTC_price">Loading price data...</h1>
        
        <p></p>
        
    <!-- Action Buttons -->

    
        {% csrf_token %}
        <div class="form-group">
            <label for="transactionQuantity">Quantity:</label>
            <input id="transactionQuantity" name = "transactionQuantity" type="text" class="col-sm-2 col-form-label col-form-label-lg"   placeholder="Enter desired quantity">
            <small class="form-text text-muted">All transactions are final</small>
        </div>
    
        <button type="submit" name="submit_type" value="buy" class="btn btn-success">Buy</button> or
        <button type="submit" name="submit_type" value="sell" class="btn btn-danger">Sell</button>
    </form>
    

    

    
</div>


<p>Current Coin balances: </p>

{% for currency in user.coin_set.all %}
<p>{{currency.coin_name}} :  {{currency.quantity}}</p>
{% endfor %}




{% load static %}
<script src="{% static "market/js/script.js" %}"></script>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    
        
  <title>{% block title %}Coin-cidence {% endblock %}</title>
  
</head>


<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
  
  <!-- Bootstrap JavaScript -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

templates/signup.html
{% extends 'base.html' %}

{% block content %}


<h2>Sign up</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
</form>


{% endblock %}